spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/develop?currentSchema=cecdcc&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    username: postgres
    password: postgres
    filters: stat,wall
    initialSize: 10
    minIdle: 10
    maxActive: 150
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    maxWait: 60000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000